### PR TITLE
Feature/336 add basic triage form validation

### PR DESCRIPTION
**Pull request by jamiebuckley**
Triage form validation is complex with the previous implementation using need indexes when constructing the forms.

The reason behind the original implementation, was to be able to submit an array of hashes, some of which have fields edited via radio buttons.
This means that rails array syntax of `array_field[][value]` wouldn't work out of the box.

However, once validation is required, having fields that look like:
`f.text_field "need[#{index}]"` becomes complex, as validation requires posting and then repopulating values on a page if there is a validation error

This implementation aims to replace the indexes by wrapping each need with a `fields_for`, which should mean that each need form section won't need to concern itself with the array indexes

### CODE REVIEW

**Comment by rik86future** [comment]
@jamiebuckley I have updated this branch with master but it's still failing some checks

**Comment by jamiebuckley** [comment]
Thanks @rik86future, I expected that, working through some cucumber failures now

**Comment by jamiebuckley** [comment]
Oh dear :( I'll take a look

**Comment by rik86future** [comment]
Another one if you remove the placeholder in the date and click save 

image

**Comment by jamiebuckley** [comment]
@rik86future this should improve things now

**Comment by rik86future** [comment]
@jamiebuckley if I remove the first name, now the validation message does not appear at all. see https://github.com/wearefuturegov/beacon/pull/123

**Pull request merged**
