### PR TITLE
Feature/style guide

### PR DESCRIPTION
**Pull request by dmgarland**
Enough plumbing to bring in the style guide

### CODE REVIEW

**Comment by userman123** [comment]
Can run locally, new styles look good. However some things not quite right, like when I hover over an imported item there is no highlight or cursor change - not clear you can click on it. Also the file uploader seems to be broken. Please see screenshots. Can't see rejected contacts either, guessing that's what you are doing next? Could you rebase onto master please also as I think there are gonna be a lot of conflicts with Mark's work that's already merged in.

Before:
Screenshot 2020-12-17 at 13 28 14

Now:
Screenshot 2020-12-17 at 13 28 41
Screenshot 2020-12-17 at 13 28 45

File does not appear to attach after selecting:
Screenshot 2020-12-17 at 13 30 21
Screenshot 2020-12-17 at 13 30 31

**Comment by dmgarland** [comment]
Thanks for the catch @userman123. I was using `DOMContentLoaded` instead of `turbolinks:load` - keep forgetting this is a turbolinks app!

**Comment by dmgarland** [comment]
Regarding hover states, they aren't in the new design so I'll check with Nick to see whether we're keeping them

**Comment by dmgarland** [comment]
And finally regarding the conflicts, I think I'll just drop Marks' last commit because I've implemented the new designs with those fields anyway

**Comment by WorkSutton** [comment]
> And finally regarding the conflicts, I think I'll just drop Marks' last commit because I've implemented the new designs with those fields anyway

Yeap @dmgarland thats the best way forward as you have covered this off in your work here. Sorry for causing the overlap

**Review by WorkSutton — APPROVED** [review]
LGTM @dmgarland

**Pull request merged**
