### PR TITLE
Fixed IE 11 select boxes and placeholder styling conerns

### PR DESCRIPTION
**Pull request by slav-petkov-saorsa**
Background:
https://trello.com/c/WVVMmJfY/308-ie-11-concerns

Solution:
- An extra arrow was appearing on IE 11 select boxes. Added the required pseudo-class to hide it.
- Added required vendor prefixes to style placeholders across different browsers

### CODE REVIEW

**Comment by slav-petkov-saorsa** [comment]
[IE 11: concerns](https://trello.com/c/WVVMmJfY/308-ie-11-concerns)

**Comment by rik86future** [comment]
@slav-petkov-saorsa all input fields seems to be really light color
image

I think the ticket meant only placehodler text to be light grey, do you think you could fix this?

**Comment by slav-petkov-saorsa** [comment]
> @slav-petkov-saorsa all input fields seems to be really light color
> image
> 
> I think the ticket meant only placehodler text to be light grey, do you think you could fix this?

Yes, I'll look into it.

**Comment by slav-petkov-saorsa** [comment]
> > @slav-petkov-saorsa all input fields seems to be really light color
> > image
> > I think the ticket meant only placehodler text to be light grey, do you think you could fix this?
> 
> Yes, I'll look into it.

@riccardo-noviello-contractor , ready for your review

**Comment by slav-petkov-saorsa** [comment]
> > > @slav-petkov-saorsa all input fields seems to be really light color
> > > image
> > > I think the ticket meant only placehodler text to be light grey, do you think you could fix this?
> > 
> > 
> > Yes, I'll look into it.
> 
> @riccardo-noviello-contractor , ready for your review

> > > @slav-petkov-saorsa all input fields seems to be really light color
> > > image
> > > I think the ticket meant only placehodler text to be light grey, do you think you could fix this?
> > 
> > 
> > Yes, I'll look into it.
> 
> @rik86future  , ready for your review

@

**Comment by rik86future** [comment]
Tested and approved

**Pull request merged**
