### PR TITLE
investigate brakeman report

### PR DESCRIPTION
**Pull request by rik86future**

### CODE REVIEW

**Comment by timwis** [comment]
I _think_ @jamiebuckley actually already whitelisted these elsewhere, in the controller or model. Let's give him a chance to review this before merging.

**Comment by rik86future** [comment]
> I _think_ @jamiebuckley actually already whitelisted these elsewhere, in the controller or model. Let's give him a chance to review this before merging.

They used to be there in the controller but I could not find them again, I think they are just embedded in the HTML which can be easily manipulated...

**Comment by jamiebuckley** [comment]
These are currently whitelisted in the filterable concern, but it doesn't hurt filtering them in multiple places I suppose

**Comment by jamiebuckley** [comment]
One thing we could do if we want to whitelist these in multiple places, is put the 'ASC|DESC` logic in a helper, e.g. `safe_order_direction`

**Comment by rik86future** [comment]
> These are currently whitelisted in the filterable concern
> https://github.com/wearefuturegov/beacon/blob/master/app/models/concerns/filterable.rb#L34
> it doesn't hurt filtering them in multiple places I suppose

PR updated, I left the RSpec for ordering but removed the ASC / DESC check

**Comment by rik86future** [comment]
[Investigate brakeman report](https://trello.com/c/DAeRzHK5/296-investigate-brakeman-report)

**Pull request closed without merging**
