### PR TITLE
Uses default time formatter for visual DOB

### PR DESCRIPTION
**Pull request by kittysquee**
Closes [Trello 164](https://trello.com/c/trEZv0pz/164-small-improvement-change-the-date-of-birth-day-month-year-to-be-dd-mm-yyyy-throughout)

I just used the default time formatter in the config folder (`config/initializers/time_formats.rb`)

### CODE REVIEW

**Review by tosbourn — APPROVED** [review]
Looks good!

If this project ever adopting a decorator pattern this would be a perfect place to throw the logic. As it stands this fits with the rest of the codebase well.

**Review by em-cd — COMMENTED** [review]
Agree with @tosbourn, perhaps in this case it would be worth popping the formatting into a helper method? I spotted that there's already a `ContactsHelper` module, it could live in there. That way if we ever need to change how the DOB is formatted, we'll only need to change it in one place.

**Comment by kittysquee** [comment]
@em-cd I've created a method which calls the date formatter as suggested.

**Review by em-cd — APPROVED** [review]
Perfect! Thanks 😄

**Pull request merged**
